version: '3.8'

services:
  nominatim:
    image: mediagis/nominatim:5.1
    container_name: nominatim_compose
    ports:
      - "8080:8080"
    environment:
      PBF_URL: https://download.geofabrik.de/south-america/brazil-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/south-america/brazil-updates
      http_proxy: http://192.168.1.254:3128       # opcional, se necessário
      https_proxy: http://192.168.1.254:3128     # opcional, se necessário
    tty: true
    stdin_open: true

